version: '3.7'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: zookeeper_docker
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my-network

  kafka:
    image: 'bitnami/kafka:3.3'
    container_name: kafka_docker
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_docker:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka_docker:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: call_faults_db
      MYSQL_USER: user # Creates a user with the specified name.
      MYSQL_PASSWORD: password # Sets the password for the created user.
    ports:
      - '3306:3306'
    networks:
      - my-network

  producer-app:
    build:
      context: ./kafka-producer
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/call_faults_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_docker:9092
    networks:
      - my-network

  consumer-app:
    build:
      context: ./kafka-consumer
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/call_faults_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_docker:9092
    networks:
      - my-network

  operator-app:
    build:
      context: ./OperatorWebApp
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/call_faults_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_docker:9092
    networks:
      - my-network

networks:
  my-network:
    driver: bridge