pipeline {
    agent any

    environment {
        MAVEN_HOME = '/usr/local/opt/maven'
    }

    stages {
        stage('Clean') {
            steps {
                script {
                    echo 'Cleaning the workspace...'
                    sh "${MAVEN_HOME}/bin/mvn clean"
                }
            }
        }

        stage('Compile') {
            steps {
                script {
                    echo 'Compiling the source code...'
                    sh "${MAVEN_HOME}/bin/mvn compile"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo 'Running tests...'
                    sh "${MAVEN_HOME}/bin/mvn test"
                }
            }
        }

        stage('Package') {
            steps {
                script {
                    echo 'Packaging the application...'
                    sh "${MAVEN_HOME}/bin/mvn package"
                }
            }
        }
    }

    post {
        always {
            script {
                echo 'Cleaning up the workspace...'
                deleteDir()
            }
        }
    }
}
